name: Fun0nydg的博客
description: 个人随笔
meta_description: "Blogging about pentest"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "https://fun0nydg.github.io/m"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://github.com/Fun0nydg"
author: "Fun0nydg"

# Disqus config
disqus-shortname: ""
